/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.15.12
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QPushButton *pB_0;
    QPushButton *pB_1;
    QPushButton *pB_2;
    QPushButton *pB_3;
    QPushButton *pB_4;
    QPushButton *pB_5;
    QPushButton *pB_6;
    QPushButton *pB_7;
    QPushButton *pB_8;
    QPushButton *pB_9;
    QPushButton *pB_dot;
    QPushButton *pB_plus;
    QPushButton *pB_minus;
    QPushButton *pB_mult;
    QPushButton *pB_div;
    QLabel *display;
    QPushButton *pB_result;
    QPushButton *pB_clear;
    QPushButton *pB_open_bracket;
    QPushButton *pB_close_bracket;
    QPushButton *pB_pow;
    QPushButton *pB_mod;
    QPushButton *pB_unary_plus;
    QPushButton *pB_unary_minus;
    QPushButton *pB_cos;
    QPushButton *pB_log;
    QPushButton *pB_ln;
    QPushButton *pB_sqrt;
    QPushButton *pB_atan;
    QPushButton *pB_asin;
    QPushButton *pB_acos;
    QPushButton *pB_tan;
    QPushButton *pB_sin;
    QPushButton *pB_x;
    QWidget *gridLayoutWidget;
    QGridLayout *gridLayout;
    QRadioButton *rB_deposit;
    QRadioButton *rb_plot;
    QRadioButton *rB_math;
    QRadioButton *rB_credit;
    QDoubleSpinBox *dSB_xValue;
    QButtonGroup *bG_numbers;
    QButtonGroup *buttonGroup;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(748, 365);
        QFont font;
        font.setFamily(QString::fromUtf8("Fira Code"));
        MainWindow->setFont(font);
        MainWindow->setStyleSheet(QString::fromUtf8(""));
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        pB_0 = new QPushButton(centralwidget);
        bG_numbers = new QButtonGroup(MainWindow);
        bG_numbers->setObjectName(QString::fromUtf8("bG_numbers"));
        bG_numbers->addButton(pB_0);
        pB_0->setObjectName(QString::fromUtf8("pB_0"));
        pB_0->setEnabled(true);
        pB_0->setGeometry(QRect(10, 310, 70, 50));
        QSizePolicy sizePolicy(QSizePolicy::Minimum, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(pB_0->sizePolicy().hasHeightForWidth());
        pB_0->setSizePolicy(sizePolicy);
        pB_0->setMinimumSize(QSize(0, 0));
        pB_0->setBaseSize(QSize(40, 40));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Fira Code"));
        font1.setPointSize(20);
        font1.setBold(false);
        font1.setStrikeOut(false);
        font1.setKerning(true);
        pB_0->setFont(font1);
        pB_0->setIconSize(QSize(16, 16));
        pB_0->setAutoDefault(false);
        pB_0->setFlat(false);
        pB_1 = new QPushButton(centralwidget);
        bG_numbers->addButton(pB_1);
        pB_1->setObjectName(QString::fromUtf8("pB_1"));
        pB_1->setEnabled(true);
        pB_1->setGeometry(QRect(10, 260, 70, 50));
        sizePolicy.setHeightForWidth(pB_1->sizePolicy().hasHeightForWidth());
        pB_1->setSizePolicy(sizePolicy);
        pB_1->setMinimumSize(QSize(0, 0));
        pB_1->setBaseSize(QSize(40, 40));
        pB_1->setFont(font1);
        pB_1->setIconSize(QSize(16, 16));
        pB_1->setAutoDefault(false);
        pB_1->setFlat(false);
        pB_2 = new QPushButton(centralwidget);
        bG_numbers->addButton(pB_2);
        pB_2->setObjectName(QString::fromUtf8("pB_2"));
        pB_2->setEnabled(true);
        pB_2->setGeometry(QRect(90, 260, 70, 50));
        sizePolicy.setHeightForWidth(pB_2->sizePolicy().hasHeightForWidth());
        pB_2->setSizePolicy(sizePolicy);
        pB_2->setMinimumSize(QSize(0, 0));
        pB_2->setBaseSize(QSize(40, 40));
        pB_2->setFont(font1);
        pB_2->setIconSize(QSize(16, 16));
        pB_2->setAutoDefault(false);
        pB_2->setFlat(false);
        pB_3 = new QPushButton(centralwidget);
        bG_numbers->addButton(pB_3);
        pB_3->setObjectName(QString::fromUtf8("pB_3"));
        pB_3->setEnabled(true);
        pB_3->setGeometry(QRect(170, 260, 70, 50));
        sizePolicy.setHeightForWidth(pB_3->sizePolicy().hasHeightForWidth());
        pB_3->setSizePolicy(sizePolicy);
        pB_3->setMinimumSize(QSize(0, 0));
        pB_3->setBaseSize(QSize(40, 40));
        pB_3->setFont(font1);
        pB_3->setIconSize(QSize(16, 16));
        pB_3->setAutoDefault(false);
        pB_3->setFlat(false);
        pB_4 = new QPushButton(centralwidget);
        bG_numbers->addButton(pB_4);
        pB_4->setObjectName(QString::fromUtf8("pB_4"));
        pB_4->setEnabled(true);
        pB_4->setGeometry(QRect(10, 210, 70, 50));
        sizePolicy.setHeightForWidth(pB_4->sizePolicy().hasHeightForWidth());
        pB_4->setSizePolicy(sizePolicy);
        pB_4->setMinimumSize(QSize(0, 0));
        pB_4->setBaseSize(QSize(40, 40));
        pB_4->setFont(font1);
        pB_4->setIconSize(QSize(16, 16));
        pB_4->setAutoDefault(false);
        pB_4->setFlat(false);
        pB_5 = new QPushButton(centralwidget);
        bG_numbers->addButton(pB_5);
        pB_5->setObjectName(QString::fromUtf8("pB_5"));
        pB_5->setEnabled(true);
        pB_5->setGeometry(QRect(90, 210, 70, 50));
        sizePolicy.setHeightForWidth(pB_5->sizePolicy().hasHeightForWidth());
        pB_5->setSizePolicy(sizePolicy);
        pB_5->setMinimumSize(QSize(0, 0));
        pB_5->setBaseSize(QSize(40, 40));
        pB_5->setFont(font1);
        pB_5->setIconSize(QSize(16, 16));
        pB_5->setAutoDefault(false);
        pB_5->setFlat(false);
        pB_6 = new QPushButton(centralwidget);
        bG_numbers->addButton(pB_6);
        pB_6->setObjectName(QString::fromUtf8("pB_6"));
        pB_6->setEnabled(true);
        pB_6->setGeometry(QRect(170, 210, 70, 50));
        sizePolicy.setHeightForWidth(pB_6->sizePolicy().hasHeightForWidth());
        pB_6->setSizePolicy(sizePolicy);
        pB_6->setMinimumSize(QSize(0, 0));
        pB_6->setBaseSize(QSize(40, 40));
        pB_6->setFont(font1);
        pB_6->setIconSize(QSize(16, 16));
        pB_6->setAutoDefault(false);
        pB_6->setFlat(false);
        pB_7 = new QPushButton(centralwidget);
        bG_numbers->addButton(pB_7);
        pB_7->setObjectName(QString::fromUtf8("pB_7"));
        pB_7->setEnabled(true);
        pB_7->setGeometry(QRect(10, 160, 70, 50));
        sizePolicy.setHeightForWidth(pB_7->sizePolicy().hasHeightForWidth());
        pB_7->setSizePolicy(sizePolicy);
        pB_7->setMinimumSize(QSize(0, 0));
        pB_7->setBaseSize(QSize(40, 40));
        pB_7->setFont(font1);
        pB_7->setStyleSheet(QString::fromUtf8(""));
        pB_7->setIconSize(QSize(16, 16));
        pB_7->setAutoDefault(false);
        pB_7->setFlat(false);
        pB_8 = new QPushButton(centralwidget);
        bG_numbers->addButton(pB_8);
        pB_8->setObjectName(QString::fromUtf8("pB_8"));
        pB_8->setEnabled(true);
        pB_8->setGeometry(QRect(90, 160, 70, 50));
        sizePolicy.setHeightForWidth(pB_8->sizePolicy().hasHeightForWidth());
        pB_8->setSizePolicy(sizePolicy);
        pB_8->setMinimumSize(QSize(0, 0));
        pB_8->setBaseSize(QSize(40, 40));
        pB_8->setFont(font1);
        pB_8->setIconSize(QSize(16, 16));
        pB_8->setAutoDefault(false);
        pB_8->setFlat(false);
        pB_9 = new QPushButton(centralwidget);
        bG_numbers->addButton(pB_9);
        pB_9->setObjectName(QString::fromUtf8("pB_9"));
        pB_9->setEnabled(true);
        pB_9->setGeometry(QRect(170, 160, 70, 50));
        sizePolicy.setHeightForWidth(pB_9->sizePolicy().hasHeightForWidth());
        pB_9->setSizePolicy(sizePolicy);
        pB_9->setMinimumSize(QSize(0, 0));
        pB_9->setBaseSize(QSize(40, 40));
        pB_9->setFont(font1);
        pB_9->setIconSize(QSize(16, 16));
        pB_9->setAutoDefault(false);
        pB_9->setFlat(false);
        pB_dot = new QPushButton(centralwidget);
        buttonGroup = new QButtonGroup(MainWindow);
        buttonGroup->setObjectName(QString::fromUtf8("buttonGroup"));
        buttonGroup->addButton(pB_dot);
        pB_dot->setObjectName(QString::fromUtf8("pB_dot"));
        pB_dot->setEnabled(true);
        pB_dot->setGeometry(QRect(90, 310, 70, 50));
        sizePolicy.setHeightForWidth(pB_dot->sizePolicy().hasHeightForWidth());
        pB_dot->setSizePolicy(sizePolicy);
        pB_dot->setMinimumSize(QSize(0, 0));
        pB_dot->setBaseSize(QSize(40, 40));
        pB_dot->setFont(font1);
        pB_dot->setStyleSheet(QString::fromUtf8(""));
        pB_dot->setIconSize(QSize(16, 16));
        pB_dot->setAutoDefault(false);
        pB_dot->setFlat(false);
        pB_plus = new QPushButton(centralwidget);
        buttonGroup->addButton(pB_plus);
        pB_plus->setObjectName(QString::fromUtf8("pB_plus"));
        pB_plus->setEnabled(true);
        pB_plus->setGeometry(QRect(250, 310, 70, 50));
        sizePolicy.setHeightForWidth(pB_plus->sizePolicy().hasHeightForWidth());
        pB_plus->setSizePolicy(sizePolicy);
        pB_plus->setMinimumSize(QSize(0, 0));
        pB_plus->setBaseSize(QSize(40, 40));
        pB_plus->setFont(font1);
        pB_plus->setStyleSheet(QString::fromUtf8(""));
        pB_plus->setIconSize(QSize(16, 16));
        pB_plus->setAutoDefault(false);
        pB_plus->setFlat(false);
        pB_minus = new QPushButton(centralwidget);
        buttonGroup->addButton(pB_minus);
        pB_minus->setObjectName(QString::fromUtf8("pB_minus"));
        pB_minus->setEnabled(true);
        pB_minus->setGeometry(QRect(250, 260, 70, 50));
        sizePolicy.setHeightForWidth(pB_minus->sizePolicy().hasHeightForWidth());
        pB_minus->setSizePolicy(sizePolicy);
        pB_minus->setMinimumSize(QSize(0, 0));
        pB_minus->setBaseSize(QSize(40, 40));
        pB_minus->setFont(font1);
        pB_minus->setStyleSheet(QString::fromUtf8(""));
        pB_minus->setIconSize(QSize(16, 16));
        pB_minus->setAutoDefault(false);
        pB_minus->setFlat(false);
        pB_mult = new QPushButton(centralwidget);
        buttonGroup->addButton(pB_mult);
        pB_mult->setObjectName(QString::fromUtf8("pB_mult"));
        pB_mult->setEnabled(true);
        pB_mult->setGeometry(QRect(250, 210, 70, 50));
        sizePolicy.setHeightForWidth(pB_mult->sizePolicy().hasHeightForWidth());
        pB_mult->setSizePolicy(sizePolicy);
        pB_mult->setMinimumSize(QSize(0, 0));
        pB_mult->setBaseSize(QSize(40, 40));
        pB_mult->setFont(font1);
        pB_mult->setStyleSheet(QString::fromUtf8(""));
        pB_mult->setIconSize(QSize(16, 16));
        pB_mult->setAutoDefault(false);
        pB_mult->setFlat(false);
        pB_div = new QPushButton(centralwidget);
        buttonGroup->addButton(pB_div);
        pB_div->setObjectName(QString::fromUtf8("pB_div"));
        pB_div->setEnabled(true);
        pB_div->setGeometry(QRect(250, 160, 70, 50));
        sizePolicy.setHeightForWidth(pB_div->sizePolicy().hasHeightForWidth());
        pB_div->setSizePolicy(sizePolicy);
        pB_div->setMinimumSize(QSize(0, 0));
        pB_div->setBaseSize(QSize(40, 40));
        pB_div->setFont(font1);
        pB_div->setStyleSheet(QString::fromUtf8(""));
        pB_div->setIconSize(QSize(16, 16));
        pB_div->setAutoDefault(false);
        pB_div->setFlat(false);
        display = new QLabel(centralwidget);
        display->setObjectName(QString::fromUtf8("display"));
        display->setGeometry(QRect(10, 10, 551, 41));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Fira Code"));
        font2.setPointSize(24);
        display->setFont(font2);
        display->setStyleSheet(QString::fromUtf8(""));
        display->setFrameShape(QFrame::Box);
        display->setLineWidth(1);
        display->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        pB_result = new QPushButton(centralwidget);
        pB_result->setObjectName(QString::fromUtf8("pB_result"));
        pB_result->setEnabled(true);
        pB_result->setGeometry(QRect(330, 164, 70, 192));
        sizePolicy.setHeightForWidth(pB_result->sizePolicy().hasHeightForWidth());
        pB_result->setSizePolicy(sizePolicy);
        pB_result->setMinimumSize(QSize(0, 0));
        pB_result->setBaseSize(QSize(40, 40));
        pB_result->setFont(font1);
        pB_result->setStyleSheet(QString::fromUtf8("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 255, 255), stop:0.339795 rgba(255, 255, 255, 255), stop:0.339799 rgba(0, 0, 255, 255), stop:0.662444 rgba(0, 0, 255, 255), stop:0.662469 rgba(255, 0, 0, 255), stop:1 rgba(255, 0, 0, 255));\n"
"color: yellow"));
        pB_result->setIconSize(QSize(16, 16));
        pB_result->setAutoDefault(false);
        pB_result->setFlat(false);
        pB_clear = new QPushButton(centralwidget);
        pB_clear->setObjectName(QString::fromUtf8("pB_clear"));
        pB_clear->setEnabled(true);
        pB_clear->setGeometry(QRect(330, 110, 70, 50));
        sizePolicy.setHeightForWidth(pB_clear->sizePolicy().hasHeightForWidth());
        pB_clear->setSizePolicy(sizePolicy);
        pB_clear->setMinimumSize(QSize(0, 0));
        pB_clear->setBaseSize(QSize(40, 40));
        pB_clear->setFont(font1);
        pB_clear->setStyleSheet(QString::fromUtf8(""));
        pB_clear->setIconSize(QSize(16, 16));
        pB_clear->setAutoDefault(false);
        pB_clear->setFlat(false);
        pB_open_bracket = new QPushButton(centralwidget);
        pB_open_bracket->setObjectName(QString::fromUtf8("pB_open_bracket"));
        pB_open_bracket->setEnabled(true);
        pB_open_bracket->setGeometry(QRect(10, 110, 70, 50));
        sizePolicy.setHeightForWidth(pB_open_bracket->sizePolicy().hasHeightForWidth());
        pB_open_bracket->setSizePolicy(sizePolicy);
        pB_open_bracket->setMinimumSize(QSize(0, 0));
        pB_open_bracket->setBaseSize(QSize(40, 40));
        pB_open_bracket->setFont(font1);
        pB_open_bracket->setStyleSheet(QString::fromUtf8(""));
        pB_open_bracket->setIconSize(QSize(16, 16));
        pB_open_bracket->setAutoDefault(false);
        pB_open_bracket->setFlat(false);
        pB_close_bracket = new QPushButton(centralwidget);
        pB_close_bracket->setObjectName(QString::fromUtf8("pB_close_bracket"));
        pB_close_bracket->setEnabled(true);
        pB_close_bracket->setGeometry(QRect(90, 110, 70, 50));
        sizePolicy.setHeightForWidth(pB_close_bracket->sizePolicy().hasHeightForWidth());
        pB_close_bracket->setSizePolicy(sizePolicy);
        pB_close_bracket->setMinimumSize(QSize(0, 0));
        pB_close_bracket->setBaseSize(QSize(40, 40));
        pB_close_bracket->setFont(font1);
        pB_close_bracket->setStyleSheet(QString::fromUtf8(""));
        pB_close_bracket->setIconSize(QSize(16, 16));
        pB_close_bracket->setAutoDefault(false);
        pB_close_bracket->setFlat(false);
        pB_pow = new QPushButton(centralwidget);
        pB_pow->setObjectName(QString::fromUtf8("pB_pow"));
        pB_pow->setEnabled(true);
        pB_pow->setGeometry(QRect(170, 110, 70, 50));
        sizePolicy.setHeightForWidth(pB_pow->sizePolicy().hasHeightForWidth());
        pB_pow->setSizePolicy(sizePolicy);
        pB_pow->setMinimumSize(QSize(0, 0));
        pB_pow->setBaseSize(QSize(40, 40));
        pB_pow->setFont(font1);
        pB_pow->setStyleSheet(QString::fromUtf8(""));
        pB_pow->setIconSize(QSize(16, 16));
        pB_pow->setAutoDefault(false);
        pB_pow->setFlat(false);
        pB_mod = new QPushButton(centralwidget);
        pB_mod->setObjectName(QString::fromUtf8("pB_mod"));
        pB_mod->setEnabled(true);
        pB_mod->setGeometry(QRect(250, 110, 70, 50));
        sizePolicy.setHeightForWidth(pB_mod->sizePolicy().hasHeightForWidth());
        pB_mod->setSizePolicy(sizePolicy);
        pB_mod->setMinimumSize(QSize(0, 0));
        pB_mod->setBaseSize(QSize(40, 40));
        pB_mod->setFont(font1);
        pB_mod->setStyleSheet(QString::fromUtf8(""));
        pB_mod->setIconSize(QSize(16, 16));
        pB_mod->setAutoDefault(false);
        pB_mod->setFlat(false);
        pB_unary_plus = new QPushButton(centralwidget);
        pB_unary_plus->setObjectName(QString::fromUtf8("pB_unary_plus"));
        pB_unary_plus->setEnabled(true);
        pB_unary_plus->setGeometry(QRect(410, 110, 70, 50));
        sizePolicy.setHeightForWidth(pB_unary_plus->sizePolicy().hasHeightForWidth());
        pB_unary_plus->setSizePolicy(sizePolicy);
        pB_unary_plus->setMinimumSize(QSize(0, 0));
        pB_unary_plus->setBaseSize(QSize(40, 40));
        pB_unary_plus->setFont(font1);
        pB_unary_plus->setIconSize(QSize(16, 16));
        pB_unary_plus->setAutoDefault(false);
        pB_unary_plus->setFlat(false);
        pB_unary_minus = new QPushButton(centralwidget);
        pB_unary_minus->setObjectName(QString::fromUtf8("pB_unary_minus"));
        pB_unary_minus->setEnabled(true);
        pB_unary_minus->setGeometry(QRect(170, 310, 70, 50));
        sizePolicy.setHeightForWidth(pB_unary_minus->sizePolicy().hasHeightForWidth());
        pB_unary_minus->setSizePolicy(sizePolicy);
        pB_unary_minus->setMinimumSize(QSize(0, 0));
        pB_unary_minus->setBaseSize(QSize(40, 40));
        pB_unary_minus->setFont(font1);
        pB_unary_minus->setIconSize(QSize(16, 16));
        pB_unary_minus->setAutoDefault(false);
        pB_unary_minus->setFlat(false);
        pB_cos = new QPushButton(centralwidget);
        pB_cos->setObjectName(QString::fromUtf8("pB_cos"));
        pB_cos->setEnabled(true);
        pB_cos->setGeometry(QRect(410, 160, 70, 50));
        sizePolicy.setHeightForWidth(pB_cos->sizePolicy().hasHeightForWidth());
        pB_cos->setSizePolicy(sizePolicy);
        pB_cos->setMinimumSize(QSize(0, 0));
        pB_cos->setBaseSize(QSize(40, 40));
        pB_cos->setFont(font1);
        pB_cos->setIconSize(QSize(16, 16));
        pB_cos->setAutoDefault(false);
        pB_cos->setFlat(false);
        pB_log = new QPushButton(centralwidget);
        pB_log->setObjectName(QString::fromUtf8("pB_log"));
        pB_log->setEnabled(true);
        pB_log->setGeometry(QRect(410, 310, 70, 50));
        sizePolicy.setHeightForWidth(pB_log->sizePolicy().hasHeightForWidth());
        pB_log->setSizePolicy(sizePolicy);
        pB_log->setMinimumSize(QSize(0, 0));
        pB_log->setBaseSize(QSize(40, 40));
        pB_log->setFont(font1);
        pB_log->setIconSize(QSize(16, 16));
        pB_log->setAutoDefault(false);
        pB_log->setFlat(false);
        pB_ln = new QPushButton(centralwidget);
        pB_ln->setObjectName(QString::fromUtf8("pB_ln"));
        pB_ln->setEnabled(true);
        pB_ln->setGeometry(QRect(490, 310, 70, 50));
        sizePolicy.setHeightForWidth(pB_ln->sizePolicy().hasHeightForWidth());
        pB_ln->setSizePolicy(sizePolicy);
        pB_ln->setMinimumSize(QSize(0, 0));
        pB_ln->setBaseSize(QSize(40, 40));
        pB_ln->setFont(font1);
        pB_ln->setIconSize(QSize(16, 16));
        pB_ln->setAutoDefault(false);
        pB_ln->setFlat(false);
        pB_sqrt = new QPushButton(centralwidget);
        pB_sqrt->setObjectName(QString::fromUtf8("pB_sqrt"));
        pB_sqrt->setEnabled(true);
        pB_sqrt->setGeometry(QRect(490, 110, 70, 50));
        sizePolicy.setHeightForWidth(pB_sqrt->sizePolicy().hasHeightForWidth());
        pB_sqrt->setSizePolicy(sizePolicy);
        pB_sqrt->setMinimumSize(QSize(0, 0));
        pB_sqrt->setBaseSize(QSize(40, 40));
        pB_sqrt->setFont(font1);
        pB_sqrt->setIconSize(QSize(16, 16));
        pB_sqrt->setAutoDefault(false);
        pB_sqrt->setFlat(false);
        pB_atan = new QPushButton(centralwidget);
        pB_atan->setObjectName(QString::fromUtf8("pB_atan"));
        pB_atan->setEnabled(true);
        pB_atan->setGeometry(QRect(490, 260, 70, 50));
        sizePolicy.setHeightForWidth(pB_atan->sizePolicy().hasHeightForWidth());
        pB_atan->setSizePolicy(sizePolicy);
        pB_atan->setMinimumSize(QSize(0, 0));
        pB_atan->setBaseSize(QSize(40, 40));
        pB_atan->setFont(font1);
        pB_atan->setIconSize(QSize(16, 16));
        pB_atan->setAutoDefault(false);
        pB_atan->setFlat(false);
        pB_asin = new QPushButton(centralwidget);
        pB_asin->setObjectName(QString::fromUtf8("pB_asin"));
        pB_asin->setEnabled(true);
        pB_asin->setGeometry(QRect(490, 210, 70, 50));
        sizePolicy.setHeightForWidth(pB_asin->sizePolicy().hasHeightForWidth());
        pB_asin->setSizePolicy(sizePolicy);
        pB_asin->setMinimumSize(QSize(0, 0));
        pB_asin->setBaseSize(QSize(40, 40));
        pB_asin->setFont(font1);
        pB_asin->setIconSize(QSize(16, 16));
        pB_asin->setAutoDefault(false);
        pB_asin->setFlat(false);
        pB_acos = new QPushButton(centralwidget);
        pB_acos->setObjectName(QString::fromUtf8("pB_acos"));
        pB_acos->setEnabled(true);
        pB_acos->setGeometry(QRect(490, 160, 70, 50));
        sizePolicy.setHeightForWidth(pB_acos->sizePolicy().hasHeightForWidth());
        pB_acos->setSizePolicy(sizePolicy);
        pB_acos->setMinimumSize(QSize(0, 0));
        pB_acos->setBaseSize(QSize(40, 40));
        pB_acos->setFont(font1);
        pB_acos->setIconSize(QSize(16, 16));
        pB_acos->setAutoDefault(false);
        pB_acos->setFlat(false);
        pB_tan = new QPushButton(centralwidget);
        pB_tan->setObjectName(QString::fromUtf8("pB_tan"));
        pB_tan->setEnabled(true);
        pB_tan->setGeometry(QRect(410, 260, 70, 50));
        sizePolicy.setHeightForWidth(pB_tan->sizePolicy().hasHeightForWidth());
        pB_tan->setSizePolicy(sizePolicy);
        pB_tan->setMinimumSize(QSize(0, 0));
        pB_tan->setBaseSize(QSize(40, 40));
        pB_tan->setFont(font1);
        pB_tan->setIconSize(QSize(16, 16));
        pB_tan->setAutoDefault(false);
        pB_tan->setFlat(false);
        pB_sin = new QPushButton(centralwidget);
        pB_sin->setObjectName(QString::fromUtf8("pB_sin"));
        pB_sin->setEnabled(true);
        pB_sin->setGeometry(QRect(410, 210, 70, 50));
        sizePolicy.setHeightForWidth(pB_sin->sizePolicy().hasHeightForWidth());
        pB_sin->setSizePolicy(sizePolicy);
        pB_sin->setMinimumSize(QSize(0, 0));
        pB_sin->setBaseSize(QSize(40, 40));
        pB_sin->setFont(font1);
        pB_sin->setIconSize(QSize(16, 16));
        pB_sin->setAutoDefault(false);
        pB_sin->setFlat(false);
        pB_x = new QPushButton(centralwidget);
        pB_x->setObjectName(QString::fromUtf8("pB_x"));
        pB_x->setEnabled(true);
        pB_x->setGeometry(QRect(10, 60, 70, 50));
        sizePolicy.setHeightForWidth(pB_x->sizePolicy().hasHeightForWidth());
        pB_x->setSizePolicy(sizePolicy);
        pB_x->setMinimumSize(QSize(0, 0));
        pB_x->setBaseSize(QSize(40, 40));
        pB_x->setFont(font1);
        pB_x->setIconSize(QSize(16, 16));
        pB_x->setAutoDefault(false);
        pB_x->setFlat(false);
        gridLayoutWidget = new QWidget(centralwidget);
        gridLayoutWidget->setObjectName(QString::fromUtf8("gridLayoutWidget"));
        gridLayoutWidget->setGeometry(QRect(570, 10, 171, 341));
        gridLayout = new QGridLayout(gridLayoutWidget);
        gridLayout->setSpacing(0);
        gridLayout->setObjectName(QString::fromUtf8("gridLayout"));
        gridLayout->setContentsMargins(16, 0, 0, 0);
        rB_deposit = new QRadioButton(gridLayoutWidget);
        rB_deposit->setObjectName(QString::fromUtf8("rB_deposit"));

        gridLayout->addWidget(rB_deposit, 2, 0, 1, 1);

        rb_plot = new QRadioButton(gridLayoutWidget);
        rb_plot->setObjectName(QString::fromUtf8("rb_plot"));

        gridLayout->addWidget(rb_plot, 3, 0, 1, 1);

        rB_math = new QRadioButton(gridLayoutWidget);
        rB_math->setObjectName(QString::fromUtf8("rB_math"));
        rB_math->setChecked(true);

        gridLayout->addWidget(rB_math, 0, 0, 1, 1);

        rB_credit = new QRadioButton(gridLayoutWidget);
        rB_credit->setObjectName(QString::fromUtf8("rB_credit"));

        gridLayout->addWidget(rB_credit, 1, 0, 1, 1);

        dSB_xValue = new QDoubleSpinBox(centralwidget);
        dSB_xValue->setObjectName(QString::fromUtf8("dSB_xValue"));
        dSB_xValue->setGeometry(QRect(90, 60, 471, 50));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Fira Code"));
        font3.setPointSize(20);
        dSB_xValue->setFont(font3);
        dSB_xValue->setContextMenuPolicy(Qt::DefaultContextMenu);
        dSB_xValue->setFrame(false);
        dSB_xValue->setButtonSymbols(QAbstractSpinBox::NoButtons);
        dSB_xValue->setKeyboardTracking(true);
        dSB_xValue->setDecimals(7);
        dSB_xValue->setMinimum(-1000000.000000000000000);
        dSB_xValue->setMaximum(1000000000000.000000000000000);
        MainWindow->setCentralWidget(centralwidget);

        retranslateUi(MainWindow);

        pB_0->setDefault(false);
        pB_1->setDefault(false);
        pB_2->setDefault(false);
        pB_3->setDefault(false);
        pB_4->setDefault(false);
        pB_5->setDefault(false);
        pB_6->setDefault(false);
        pB_7->setDefault(false);
        pB_8->setDefault(false);
        pB_9->setDefault(false);
        pB_dot->setDefault(false);
        pB_plus->setDefault(false);
        pB_minus->setDefault(false);
        pB_mult->setDefault(false);
        pB_div->setDefault(false);
        pB_result->setDefault(false);
        pB_clear->setDefault(false);
        pB_open_bracket->setDefault(false);
        pB_close_bracket->setDefault(false);
        pB_pow->setDefault(false);
        pB_mod->setDefault(false);
        pB_unary_plus->setDefault(false);
        pB_unary_minus->setDefault(false);
        pB_cos->setDefault(false);
        pB_log->setDefault(false);
        pB_ln->setDefault(false);
        pB_sqrt->setDefault(false);
        pB_atan->setDefault(false);
        pB_asin->setDefault(false);
        pB_acos->setDefault(false);
        pB_tan->setDefault(false);
        pB_sin->setDefault(false);
        pB_x->setDefault(false);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        pB_0->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        pB_1->setText(QCoreApplication::translate("MainWindow", "1", nullptr));
        pB_2->setText(QCoreApplication::translate("MainWindow", "2", nullptr));
        pB_3->setText(QCoreApplication::translate("MainWindow", "3", nullptr));
        pB_4->setText(QCoreApplication::translate("MainWindow", "4", nullptr));
        pB_5->setText(QCoreApplication::translate("MainWindow", "5", nullptr));
        pB_6->setText(QCoreApplication::translate("MainWindow", "6", nullptr));
        pB_7->setText(QCoreApplication::translate("MainWindow", "7", nullptr));
        pB_8->setText(QCoreApplication::translate("MainWindow", "8", nullptr));
        pB_9->setText(QCoreApplication::translate("MainWindow", "9", nullptr));
        pB_dot->setText(QCoreApplication::translate("MainWindow", ".", nullptr));
        pB_plus->setText(QCoreApplication::translate("MainWindow", "+", nullptr));
        pB_minus->setText(QCoreApplication::translate("MainWindow", "-", nullptr));
        pB_mult->setText(QCoreApplication::translate("MainWindow", "x", nullptr));
        pB_div->setText(QCoreApplication::translate("MainWindow", "\303\267", nullptr));
        display->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        pB_result->setText(QCoreApplication::translate("MainWindow", "=", nullptr));
        pB_clear->setText(QCoreApplication::translate("MainWindow", "C", nullptr));
        pB_open_bracket->setText(QCoreApplication::translate("MainWindow", "(", nullptr));
        pB_close_bracket->setText(QCoreApplication::translate("MainWindow", ")", nullptr));
        pB_pow->setText(QCoreApplication::translate("MainWindow", "^", nullptr));
        pB_mod->setText(QCoreApplication::translate("MainWindow", "mod", nullptr));
        pB_unary_plus->setText(QCoreApplication::translate("MainWindow", "+a", nullptr));
        pB_unary_minus->setText(QCoreApplication::translate("MainWindow", "-a", nullptr));
        pB_cos->setText(QCoreApplication::translate("MainWindow", "cos", nullptr));
        pB_log->setText(QCoreApplication::translate("MainWindow", "log", nullptr));
        pB_ln->setText(QCoreApplication::translate("MainWindow", "ln", nullptr));
        pB_sqrt->setText(QCoreApplication::translate("MainWindow", "sqrt", nullptr));
        pB_atan->setText(QCoreApplication::translate("MainWindow", "atan", nullptr));
        pB_asin->setText(QCoreApplication::translate("MainWindow", "asin", nullptr));
        pB_acos->setText(QCoreApplication::translate("MainWindow", "acos", nullptr));
        pB_tan->setText(QCoreApplication::translate("MainWindow", "tan", nullptr));
        pB_sin->setText(QCoreApplication::translate("MainWindow", "sin", nullptr));
        pB_x->setText(QCoreApplication::translate("MainWindow", "X", nullptr));
        rB_deposit->setText(QCoreApplication::translate("MainWindow", "Deposit", nullptr));
        rb_plot->setText(QCoreApplication::translate("MainWindow", "Graph", nullptr));
        rB_math->setText(QCoreApplication::translate("MainWindow", "Math", nullptr));
        rB_credit->setText(QCoreApplication::translate("MainWindow", "Credit", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
